### ISSUE TITLE
! installation failed

### ISSUE THREAD

**Issue by dharmendra1111** [Magisk-Modules-Alt-Repo/AFWall-Boot-AntiLeak#4]
downloading zip and installing module using Magisk "install from storage" button gives error "! installation failed"

**Comment by gjf** [comment]
Does install from online work?

**Comment by dharmendra1111** [comment]
> Does install from online work?
Yes, I downloaded it all as zip file and tried installing from Magisk. Other modules installs fine, so I think update binary or script may be the cause here.

**Comment by gjf** [comment]
Don't download it, simply try to install.
If it fails - please provide installation logs. Because it looks like your own problem, nobody reports the same.
To investigate it, I need more details.

**Comment by dharmendra1111** [comment]
I am using Magisk v24.3, which doesn't support online repo (It was there in older versions). I am not aware of any other methods of installation of magisk modules, which doesn't require downloading the main.zip from github. I have installed many other modules same way and they installed fine, so I raised an issue here. I'll try to install it to some other device for testing.

logs from Magisk app... (doesn't look very usefull to me)
- Copying zip to temp directory
- Installing AFWall-Boot-AntiLeak-main.zip
! Installation failed

**Comment by gjf** [comment]
Try to use this: https://github.com/Fox2Code/FoxMagiskModuleManager

**Comment by dharmendra1111** [comment]
> Try to use this: https://github.com/Fox2Code/FoxMagiskModuleManager

Tried... It works with direct install method (module manager app needs root right for that).

Downloading module and then installing gives error. 
At first it gives zip error, but if you shift all files and folders to root directory in .zip file, zip error dissapears and it gives above discussed error.
Other module installs fine after shifting all files to root directory, but for this module that solution doesn't work for some reason!

atleast we have one method to install this module, so for now I would say problem is solved (as long as the module manager app is working). Thanks for your help.

**Comment by xfzv** [comment]
I was getting the exact same error with Magisk 26.1:

> 
    Copying zip to temp directory
    Installing AFWall-Boot-AntiLeak-main.zip
    ! Installation failed


I stumbled across this: https://github.com/Magisk-Modules-Repo/movecert/issues/12#issuecomment-1037292665

And that did the trick.

@gjf any chance you could implement this change? it would be useful for users who just want to flash the zip in Magisk without using [Androidacy/MagiskModuleManager](https://github.com/Androidacy/MagiskModuleManager).

**Comment by gjf** [comment]
This module was developed for online repo with strict following official docs: https://github.com/topjohnwu/Magisk/blob/master/docs/guides.md#notes
By the way you are complaining about that on this online repo.

I will not support offline installation as it will cause numerous problems specific for every custom firmware and device.
If you want to use it offline - you will do the modification by yourself and you will be responsible for this, not me.

**Comment by xfzv** [comment]
OK. One question if you don't mind:

> When your module is downloaded with the Magisk app, update-binary will be forcefully replaced with the latest [module_installer.sh](https://github.com/topjohnwu/Magisk/blob/master/scripts/module_installer.sh). DO NOT try to add any custom logic in update-binary.

What's the difference between this and me doing it manually?

> By the way you are complaining about that on this online repo.

I'm not complaining about anything. I was just trying to be helpful to some users who might want to install this module from the Magisk app and don't want to use [Androidacy/MagiskModuleManager](https://github.com/Androidacy/MagiskModuleManager).

Plus, I was able to install [Magisk-Modules-Alt-Repo/HideNavBar](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/blob/master/META-INF/com/google/android/update-binary) just fine before having the same issue than OP with this module, so I thought there was something wrong with `update-binary` here.

**Comment by wvengen** [comment]
Thanks to the comments here, I was able to produce a zip that at least installs directly from within Magisk: [afwall-boot-antileak.zip](https://github.com/Magisk-Modules-Alt-Repo/AFWall-Boot-AntiLeak/files/13877181/afwall-boot-antileak.zip)
(built from commit https://github.com/Magisk-Modules-Alt-Repo/AFWall-Boot-AntiLeak/commit/406e61b12e09e8eb1f5cc36c1181c38c77fa3f09)
